name: letter_management_app
description: اپلیکیشن فلاتر مدیریت نامه‌های رسمی برای کارشناسان
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jalali_date_time: ^1.0.0
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^15.1.0
  timezone: ^0.9.2
  http: ^1.1.0
  local_auth: ^2.1.8
  pdf: ^3.10.0
  printing: ^5.11.0
  provider: ^6.0.0
  json_serializable: ^6.7.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
